"""initial PostgreSQL multi-user schema"""
from alembic import op

revision = "0001_postgres_multi_user"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.execute("""
    CREATE TABLE users (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, display_name TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
    CREATE TABLE user_identities (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, provider TEXT NOT NULL, provider_subject TEXT NOT NULL, password_hash TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(provider,provider_subject));
    CREATE TABLE telegram_accounts (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, telegram_user_id BIGINT UNIQUE, telegram_chat_id BIGINT UNIQUE, telegram_username TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
    CREATE TABLE app_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
    CREATE TABLE user_settings (user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,key TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(user_id,key));
    CREATE TABLE cards (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,question TEXT NOT NULL,answer TEXT NOT NULL,stage INTEGER NOT NULL DEFAULT 0,due_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL,tags TEXT,ease_factor DOUBLE PRECISION NOT NULL DEFAULT 2.5,interval_days INTEGER NOT NULL DEFAULT 1,repetitions INTEGER NOT NULL DEFAULT 0,card_type TEXT NOT NULL DEFAULT 'basic',image_file_id TEXT,consecutive_again INTEGER NOT NULL DEFAULT 0,stability DOUBLE PRECISION,difficulty DOUBLE PRECISION,last_review TIMESTAMPTZ,notes TEXT,suspended BOOLEAN NOT NULL DEFAULT FALSE,buried_until TIMESTAMPTZ,reverse_of BIGINT REFERENCES cards(id) ON DELETE SET NULL);
    CREATE INDEX cards_user_due_active_idx ON cards(user_id,due_at) WHERE suspended=FALSE; CREATE INDEX cards_user_suspended_idx ON cards(user_id,id) WHERE suspended=TRUE; CREATE INDEX cards_reverse_of_idx ON cards(reverse_of) WHERE reverse_of IS NOT NULL;
    CREATE TABLE review_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,card_id BIGINT NOT NULL REFERENCES cards(id) ON DELETE CASCADE,quality SMALLINT NOT NULL CHECK(quality IN(1,3,4,5)),reviewed_at TIMESTAMPTZ NOT NULL); CREATE INDEX review_log_user_reviewed_idx ON review_log(user_id,reviewed_at); CREATE INDEX review_log_user_card_reviewed_idx ON review_log(user_id,card_id,reviewed_at);
    CREATE TABLE undo_snapshots (user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,card_id BIGINT NOT NULL REFERENCES cards(id) ON DELETE CASCADE,ease_factor DOUBLE PRECISION NOT NULL,interval_days INTEGER NOT NULL,repetitions INTEGER NOT NULL,due_at TIMESTAMPTZ NOT NULL,stage INTEGER NOT NULL,consecutive_again INTEGER NOT NULL,review_log_id BIGINT REFERENCES review_log(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL,stability DOUBLE PRECISION,difficulty DOUBLE PRECISION,last_review TIMESTAMPTZ);
    CREATE TABLE session_notes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,telegram_account_id BIGINT REFERENCES telegram_accounts(id) ON DELETE SET NULL,topic TEXT NOT NULL,content TEXT NOT NULL,tags TEXT,created_at TIMESTAMPTZ NOT NULL); CREATE INDEX session_notes_user_created_idx ON session_notes(user_id,created_at DESC);
    CREATE TABLE web_sessions (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_prefix TEXT NOT NULL,token_hash BYTEA NOT NULL UNIQUE,created_at TIMESTAMPTZ NOT NULL,expires_at TIMESTAMPTZ NOT NULL,revoked_at TIMESTAMPTZ,last_used_at TIMESTAMPTZ,UNIQUE(token_prefix,token_hash)); CREATE INDEX web_sessions_prefix_idx ON web_sessions(token_prefix) WHERE revoked_at IS NULL;
    CREATE TABLE api_tokens (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,token_prefix TEXT NOT NULL,token_hash BYTEA NOT NULL UNIQUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),expires_at TIMESTAMPTZ,last_used_at TIMESTAMPTZ,revoked_at TIMESTAMPTZ,UNIQUE(token_prefix,token_hash)); CREATE INDEX api_tokens_prefix_idx ON api_tokens(token_prefix) WHERE revoked_at IS NULL;
    CREATE TABLE import_runs (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, source_fingerprint TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
    """)
def downgrade():
    op.execute("DROP TABLE IF EXISTS import_runs,api_tokens,web_sessions,session_notes,undo_snapshots,review_log,cards,user_settings,app_settings,telegram_accounts,user_identities,users CASCADE")
